<?php

/**
 * BaseImageArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string       getName() Returns the current record's "name" value
 * @method ImageArticle setName() Sets the current record's "name" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_article');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sfimagepoolable0 = new sfImagePoolable(array(
             'multiple' => true,
             'shared_images' => false,
             ));
        $this->actAs($sfimagepoolable0);
    }
}