<?php

/**
 * PluginsfImagePoolCropTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfImagePoolCropTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfImagePoolCropTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfImagePoolCrop');
    }
    
    /*
     * Find a crop of an image
     * 
     * @param sfImagePoolImage $image
     * @param int $width
     * @param int $height
     * @param string $identifier
     */
    public function findCrop(sfImagePoolImage $image, $width, $height, $is_crop = true, $identifier = NULL)
    {
      $q = $this->createQuery('c')
                ->where('c.sf_image_id = ? AND width = ? AND height = ? AND is_crop = ?', array($image->getPrimaryKey(), $width, $height, $is_crop));

      if ($identifier)
      {
        $q->addWhere('location = ?', $identifier);
      }

      return $q->fetchOne();
    }    
}