<?php

/**
 * PluginsfImagePoolCrop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfImagePoolCrop extends BasesfImagePoolCrop
{
    /**
     * Call sfImagePoolCache implementation to take care of deleting files
     * This handles all caching implementations
     */
    public function postDelete($event)
    {
        $crop = $event->getInvoker();
        $cache = sfImagePoolCache::getInstance($crop->getImage());
        $cache->delete($crop);
    }
}