<?php

/**
 * ImageArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    imagepool
 * @subpackage model
 * @author     Jo Carter
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ImageArticle extends BaseImageArticle
{
}
