<?php

/**
 * ImageArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageArticle');
    }
}